"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TravelClass:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TravelClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TravelClass.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownTravelClass: _TravelClass.ValueType  # 0
    First: _TravelClass.ValueType  # 1
    Second: _TravelClass.ValueType  # 2
    Upgrade: _TravelClass.ValueType  # 3

class TravelClass(_TravelClass, metaclass=_TravelClassEnumTypeWrapper): ...

UnknownTravelClass: TravelClass.ValueType  # 0
First: TravelClass.ValueType  # 1
Second: TravelClass.ValueType  # 2
Upgrade: TravelClass.ValueType  # 3
global___TravelClass = TravelClass

class _JourneyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JourneyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JourneyType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownJourneyType: _JourneyType.ValueType  # 0
    OneWay: _JourneyType.ValueType  # 1
    Return: _JourneyType.ValueType  # 2
    TwoWay: _JourneyType.ValueType  # 3

class JourneyType(_JourneyType, metaclass=_JourneyTypeEnumTypeWrapper): ...

UnknownJourneyType: JourneyType.ValueType  # 0
OneWay: JourneyType.ValueType  # 1
Return: JourneyType.ValueType  # 2
TwoWay: JourneyType.ValueType  # 3
global___JourneyType = JourneyType

class _ValidityType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ValidityTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ValidityType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownValidityType: _ValidityType.ValueType  # 0
    SpaceAndTime: _ValidityType.ValueType  # 1
    Validation: _ValidityType.ValueType  # 2

class ValidityType(_ValidityType, metaclass=_ValidityTypeEnumTypeWrapper): ...

UnknownValidityType: ValidityType.ValueType  # 0
SpaceAndTime: ValidityType.ValueType  # 1
Validation: ValidityType.ValueType  # 2
global___ValidityType = ValidityType

class _RouteType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RouteTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RouteType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownRouteType: _RouteType.ValueType  # 0
    Undefined: _RouteType.ValueType  # 1
    RouteTicket: _RouteType.ValueType  # 2
    ZoneTicket: _RouteType.ValueType  # 3

class RouteType(_RouteType, metaclass=_RouteTypeEnumTypeWrapper): ...

UnknownRouteType: RouteType.ValueType  # 0
Undefined: RouteType.ValueType  # 1
RouteTicket: RouteType.ValueType  # 2
ZoneTicket: RouteType.ValueType  # 3
global___RouteType = RouteType

class _Language:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LanguageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Language.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownLanguage: _Language.ValueType  # 0
    DE: _Language.ValueType  # 1
    FR: _Language.ValueType  # 2
    IT: _Language.ValueType  # 3
    EN: _Language.ValueType  # 4

class Language(_Language, metaclass=_LanguageEnumTypeWrapper): ...

UnknownLanguage: Language.ValueType  # 0
DE: Language.ValueType  # 1
FR: Language.ValueType  # 2
IT: Language.ValueType  # 3
EN: Language.ValueType  # 4
global___Language = Language

class _TransportType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TransportTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TransportType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownTransportType: _TransportType.ValueType  # 0
    Railway: _TransportType.ValueType  # 1
    Bus: _TransportType.ValueType  # 2
    Tram: _TransportType.ValueType  # 3
    Boat: _TransportType.ValueType  # 4
    MountainRailway: _TransportType.ValueType  # 5

class TransportType(_TransportType, metaclass=_TransportTypeEnumTypeWrapper): ...

UnknownTransportType: TransportType.ValueType  # 0
Railway: TransportType.ValueType  # 1
Bus: TransportType.ValueType  # 2
Tram: TransportType.ValueType  # 3
Boat: TransportType.ValueType  # 4
MountainRailway: TransportType.ValueType  # 5
global___TransportType = TransportType

@typing.final
class SignedTicket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_DATA_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    KEY_META_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    signature: builtins.bytes
    """ASN.1"""
    @property
    def ticket_data(self) -> global___Ticket: ...
    @property
    def metadata(self) -> global___Metadata: ...
    @property
    def key_meta(self) -> global___KeyMeta: ...
    def __init__(
        self,
        *,
        ticket_data: global___Ticket | None = ...,
        metadata: global___Metadata | None = ...,
        key: builtins.bytes = ...,
        key_meta: global___KeyMeta | None = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["key_meta", b"key_meta", "metadata", b"metadata", "ticket_data", b"ticket_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "key_meta", b"key_meta", "metadata", b"metadata", "signature", b"signature", "ticket_data", b"ticket_data"]) -> None: ...

global___SignedTicket = SignedTicket

@typing.final
class KeyMeta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RICS_FIELD_NUMBER: builtins.int
    KEY_ID_FIELD_NUMBER: builtins.int
    rics: builtins.str
    key_id: builtins.str
    def __init__(
        self,
        *,
        rics: builtins.str = ...,
        key_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key_id", b"key_id", "rics", b"rics"]) -> None: ...

global___KeyMeta = KeyMeta

@typing.final
class Metadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    version: builtins.int
    def __init__(
        self,
        *,
        version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["version", b"version"]) -> None: ...

global___Metadata = Metadata

@typing.final
class Ticket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_ID_FIELD_NUMBER: builtins.int
    TARIFF_FIELD_NUMBER: builtins.int
    TRAVELER_FIELD_NUMBER: builtins.int
    SALE_FIELD_NUMBER: builtins.int
    PAYMENT_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    TRANSPORT_FIELD_NUMBER: builtins.int
    TRANSPORT_DATA_COUNT_FIELD_NUMBER: builtins.int
    TARIFFS_FIELD_NUMBER: builtins.int
    ticket_id: builtins.int
    transport_data_count: builtins.int
    @property
    def tariff(self) -> global___Tariff: ...
    @property
    def traveler(self) -> global___TravelerData: ...
    @property
    def sale(self) -> global___SaleData: ...
    @property
    def payment(self) -> global___PaymentData: ...
    @property
    def extra(self) -> global___ExtraData: ...
    @property
    def transport(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TransportData]: ...
    @property
    def tariffs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TariffExtra]: ...
    def __init__(
        self,
        *,
        ticket_id: builtins.int = ...,
        tariff: global___Tariff | None = ...,
        traveler: global___TravelerData | None = ...,
        sale: global___SaleData | None = ...,
        payment: global___PaymentData | None = ...,
        extra: global___ExtraData | None = ...,
        transport: collections.abc.Iterable[global___TransportData] | None = ...,
        transport_data_count: builtins.int = ...,
        tariffs: collections.abc.Iterable[global___TariffExtra] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["extra", b"extra", "payment", b"payment", "sale", b"sale", "tariff", b"tariff", "traveler", b"traveler"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["extra", b"extra", "payment", b"payment", "sale", b"sale", "tariff", b"tariff", "tariffs", b"tariffs", "ticket_id", b"ticket_id", "transport", b"transport", "transport_data_count", b"transport_data_count", "traveler", b"traveler"]) -> None: ...

global___Ticket = Ticket

@typing.final
class Tariff(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: builtins.int
    DEPARTURE_STATION_FIELD_NUMBER: builtins.int
    ARRIVAL_STATION_FIELD_NUMBER: builtins.int
    TRAVEL_CLASS_FIELD_NUMBER: builtins.int
    JOURNEY_TYPE_FIELD_NUMBER: builtins.int
    ROUTE_FIELD_NUMBER: builtins.int
    NUMBER_ROUTES_FIELD_NUMBER: builtins.int
    VALID_FROM_FIELD_NUMBER: builtins.int
    VALID_UNTIL_FIELD_NUMBER: builtins.int
    RETURN_VALID_FROM_FIELD_NUMBER: builtins.int
    RETURN_VALID_UNTIL_FIELD_NUMBER: builtins.int
    PRODUCT_NUMBER_FIELD_NUMBER: builtins.int
    ZONES_FIELD_NUMBER: builtins.int
    NUMBER_ZONES_FIELD_NUMBER: builtins.int
    TARIFF_FIELD_NUMBER: builtins.int
    REDUCED_TARIFF_FIELD_NUMBER: builtins.int
    NIGHT_SURCHARGE_FIELD_NUMBER: builtins.int
    VALIDITY_TYPE_FIELD_NUMBER: builtins.int
    ROUTE_TYPE_FIELD_NUMBER: builtins.int
    departure_station: builtins.str
    arrival_station: builtins.str
    travel_class: global___TravelClass.ValueType
    journey_type: global___JourneyType.ValueType
    number_routes: builtins.int
    product_number: builtins.int
    number_zones: builtins.int
    tariff: builtins.str
    reduced_tariff: builtins.bool
    night_surcharge: builtins.bool
    validity_type: global___ValidityType.ValueType
    route_type: global___RouteType.ValueType
    @property
    def product(self) -> global___Product: ...
    @property
    def route(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def valid_from(self) -> global___Time: ...
    @property
    def valid_until(self) -> global___Time: ...
    @property
    def return_valid_from(self) -> global___Time: ...
    @property
    def return_valid_until(self) -> global___Time: ...
    @property
    def zones(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Zone]: ...
    def __init__(
        self,
        *,
        product: global___Product | None = ...,
        departure_station: builtins.str = ...,
        arrival_station: builtins.str = ...,
        travel_class: global___TravelClass.ValueType = ...,
        journey_type: global___JourneyType.ValueType = ...,
        route: collections.abc.Iterable[builtins.str] | None = ...,
        number_routes: builtins.int = ...,
        valid_from: global___Time | None = ...,
        valid_until: global___Time | None = ...,
        return_valid_from: global___Time | None = ...,
        return_valid_until: global___Time | None = ...,
        product_number: builtins.int = ...,
        zones: collections.abc.Iterable[global___Zone] | None = ...,
        number_zones: builtins.int = ...,
        tariff: builtins.str = ...,
        reduced_tariff: builtins.bool = ...,
        night_surcharge: builtins.bool = ...,
        validity_type: global___ValidityType.ValueType = ...,
        route_type: global___RouteType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["product", b"product", "return_valid_from", b"return_valid_from", "return_valid_until", b"return_valid_until", "valid_from", b"valid_from", "valid_until", b"valid_until"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["arrival_station", b"arrival_station", "departure_station", b"departure_station", "journey_type", b"journey_type", "night_surcharge", b"night_surcharge", "number_routes", b"number_routes", "number_zones", b"number_zones", "product", b"product", "product_number", b"product_number", "reduced_tariff", b"reduced_tariff", "return_valid_from", b"return_valid_from", "return_valid_until", b"return_valid_until", "route", b"route", "route_type", b"route_type", "tariff", b"tariff", "travel_class", b"travel_class", "valid_from", b"valid_from", "valid_until", b"valid_until", "validity_type", b"validity_type", "zones", b"zones"]) -> None: ...

global___Tariff = Tariff

@typing.final
class Product(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    language: global___Language.ValueType
    name: builtins.str
    def __init__(
        self,
        *,
        language: global___Language.ValueType = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["language", b"language", "name", b"name"]) -> None: ...

global___Product = Product

@typing.final
class Zone(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALL_ZONES_FIELD_NUMBER: builtins.int
    ZONE_ID_FIELD_NUMBER: builtins.int
    ZONE_ORG_FIELD_NUMBER: builtins.int
    all_zones: builtins.bool
    zone_id: builtins.int
    zone_org: builtins.int
    def __init__(
        self,
        *,
        all_zones: builtins.bool = ...,
        zone_id: builtins.int = ...,
        zone_org: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["all_zones", b"all_zones", "zone_id", b"zone_id", "zone_org", b"zone_org"]) -> None: ...

global___Zone = Zone

@typing.final
class TravelerData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUSTOMER_NUMBER_FIELD_NUMBER: builtins.int
    SWISSPASS_ID_FIELD_NUMBER: builtins.int
    SURNAME_FIELD_NUMBER: builtins.int
    FORENAME_FIELD_NUMBER: builtins.int
    BIRTHDAY_FIELD_NUMBER: builtins.int
    MOBILE_NUMBER_FIELD_NUMBER: builtins.int
    TARIFF_FIELD_NUMBER: builtins.int
    REDUCTION_FIELD_NUMBER: builtins.int
    customer_number: builtins.str
    swisspass_id: builtins.str
    surname: builtins.str
    forename: builtins.str
    mobile_number: builtins.str
    tariff: builtins.str
    reduction: builtins.str
    @property
    def birthday(self) -> global___Time: ...
    def __init__(
        self,
        *,
        customer_number: builtins.str = ...,
        swisspass_id: builtins.str = ...,
        surname: builtins.str = ...,
        forename: builtins.str = ...,
        birthday: global___Time | None = ...,
        mobile_number: builtins.str = ...,
        tariff: builtins.str = ...,
        reduction: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["birthday", b"birthday"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["birthday", b"birthday", "customer_number", b"customer_number", "forename", b"forename", "mobile_number", b"mobile_number", "reduction", b"reduction", "surname", b"surname", "swisspass_id", b"swisspass_id", "tariff", b"tariff"]) -> None: ...

global___TravelerData = TravelerData

@typing.final
class TransportData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOURNEY_NUMBER_FIELD_NUMBER: builtins.int
    CARRIAGE_FIELD_NUMBER: builtins.int
    SEATS_FIELD_NUMBER: builtins.int
    NUMBER_SEATS_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    journey_number: builtins.str
    carriage: builtins.str
    number_seats: builtins.int
    type: global___TransportType.ValueType
    @property
    def seats(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        journey_number: builtins.str = ...,
        carriage: builtins.str = ...,
        seats: collections.abc.Iterable[builtins.str] | None = ...,
        number_seats: builtins.int = ...,
        type: global___TransportType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["carriage", b"carriage", "journey_number", b"journey_number", "number_seats", b"number_seats", "seats", b"seats", "type", b"type"]) -> None: ...

global___TransportData = TransportData

@typing.final
class SaleData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SELLING_TIME_FIELD_NUMBER: builtins.int
    LANGUAGE_FIELD_NUMBER: builtins.int
    SALE_POINT_FIELD_NUMBER: builtins.int
    ISSUING_ORG_FIELD_NUMBER: builtins.int
    language: global___Language.ValueType
    sale_point: builtins.int
    issuing_org: builtins.int
    @property
    def selling_time(self) -> global___Time: ...
    def __init__(
        self,
        *,
        selling_time: global___Time | None = ...,
        language: global___Language.ValueType = ...,
        sale_point: builtins.int = ...,
        issuing_org: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["selling_time", b"selling_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["issuing_org", b"issuing_org", "language", b"language", "sale_point", b"sale_point", "selling_time", b"selling_time"]) -> None: ...

global___SaleData = SaleData

@typing.final
class PaymentData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_METHOD_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    payment_method: builtins.str
    currency: builtins.str
    price: builtins.str
    def __init__(
        self,
        *,
        payment_method: builtins.str = ...,
        currency: builtins.str = ...,
        price: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["currency", b"currency", "payment_method", b"payment_method", "price", b"price"]) -> None: ...

global___PaymentData = PaymentData

@typing.final
class ExtraData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FALLBACK_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    SPECIMEN_FIELD_NUMBER: builtins.int
    fallback: builtins.bool
    extra: builtins.str
    specimen: builtins.bool
    def __init__(
        self,
        *,
        fallback: builtins.bool = ...,
        extra: builtins.str = ...,
        specimen: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["extra", b"extra", "fallback", b"fallback", "specimen", b"specimen"]) -> None: ...

global___ExtraData = ExtraData

@typing.final
class TariffExtra(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PASSENGER_COUNT_FIELD_NUMBER: builtins.int
    name: builtins.str
    passenger_count: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        passenger_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "passenger_count", b"passenger_count"]) -> None: ...

global___TariffExtra = TariffExtra

@typing.final
class Time(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSECS_FIELD_NUMBER: builtins.int
    msecs: builtins.int
    def __init__(
        self,
        *,
        msecs: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["msecs", b"msecs"]) -> None: ...

global___Time = Time
