# Generated by Django 5.0.14 on 2025-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255)),
                ('agency_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('timezone', models.CharField(max_length=64)),
                ('primary_language', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('fare_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'unique_together': {('feed_id', 'agency_id')},
            },
        ),
    ]
