# Generated by Django 5.0.14 on 2025-09-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(max_length=255, verbose_name='Agency ID'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='fare_url',
            field=models.URLField(blank=True, null=True, verbose_name='Fare URL'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='feed_id',
            field=models.CharField(max_length=255, verbose_name='Feed ID'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('stop_id', models.CharField(max_length=255, verbose_name='Stop ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tts_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('location_type', models.CharField(choices=[('stop', 'Stop'), ('station', 'Station'), ('entrance', 'Entrance/Exit'), ('generic-node', 'Generic Node'), ('boarding-area', 'Boarding Area')], max_length=64)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('wheelchair_boarding', models.BooleanField(blank=True, null=True)),
                ('platform_code', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.stop')),
            ],
        ),
    ]
