# Generated by Django 5.0.14 on 2025-09-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0002_alter_agency_options_alter_agency_agency_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('feed_id', 'stop_id')},
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('route_id', models.CharField(max_length=255, verbose_name='Route ID')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('route_type', models.CharField(choices=[('light-rail', 'Tram/Light Rail'), ('metro', 'Metro/Subway'), ('rail', 'Rail'), ('bus', 'Bus'), ('ferry', 'Ferry'), ('cable-tram', 'Cable Tram'), ('aerial-lift', 'Aerial Lift'), ('funicular', 'Funicular'), ('trolleybus', 'Trolleybus'), ('monorail', 'Monorail')], max_length=64)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('colour', models.CharField(blank=True, max_length=6, null=True)),
                ('text_colour', models.CharField(blank=True, max_length=6, null=True)),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.agency')),
            ],
            options={
                'unique_together': {('feed_id', 'route_id')},
            },
        ),
    ]
