# Generated by Django 5.0.14 on 2025-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0003_alter_stop_unique_together_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('trip_id', models.CharField(max_length=255, verbose_name='Trip ID')),
                ('headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(choices=[('unspecified', 'Unspecified'), ('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=64)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wheelchair_accessible', models.BooleanField(blank=True, null=True)),
                ('bikes_allowed', models.BooleanField(blank=True, null=True)),
                ('cars_allowed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('feed_id', 'trip_id')},
            },
        ),
    ]
