# Generated by Django 5.0.14 on 2025-09-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtfs.route'),
            preserve_default=False,
        ),
    ]
