# Generated by Django 5.0.14 on 2025-09-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0005_trip_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_time', models.PositiveIntegerField(blank=True, null=True)),
                ('departure_time', models.PositiveIntegerField(blank=True, null=True)),
                ('headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_traveled', models.FloatField(blank=True, null=True)),
                ('pick_up_type', models.CharField(choices=[('regular', 'Regularly scheduled'), ('forbidden', 'Forbidden'), ('phone', 'Phone agency'), ('coordinate-with-driver', 'Coordinate with driver')], max_length=255)),
                ('drop_off_type', models.CharField(choices=[('regular', 'Regularly scheduled'), ('forbidden', 'Forbidden'), ('phone', 'Phone agency'), ('coordinate-with-driver', 'Coordinate with driver')], max_length=255)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.trip')),
            ],
            options={
                'unique_together': {('trip', 'sequence')},
            },
        ),
    ]
