# Generated by Django 5.0.14 on 2025-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0006_stoptime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoptime',
            options={'ordering': ('sequence',)},
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('calendar_id', models.CharField(max_length=255, verbose_name='Calendar ID')),
                ('monday', models.BooleanField(blank=True, default=False)),
                ('tuesday', models.BooleanField(blank=True, default=False)),
                ('wednesday', models.BooleanField(blank=True, default=False)),
                ('thursday', models.BooleanField(blank=True, default=False)),
                ('friday', models.BooleanField(blank=True, default=False)),
                ('saturday', models.BooleanField(blank=True, default=False)),
                ('sunday', models.BooleanField(blank=True, default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'unique_together': {('feed_id', 'calendar_id')},
            },
        ),
    ]
