# Generated by Django 5.0.14 on 2025-09-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0007_alter_stoptime_options_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.calendar'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='friday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='monday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='saturday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sunday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thursday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='tuesday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='wednesday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Wednesday'),
        ),
    ]
