# Generated by Django 5.0.14 on 2025-09-08 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0008_trip_calendar_alter_calendar_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('service_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calendar ID')),
                ('date', models.DateField()),
                ('exception', models.CharField(choices=[('added', 'Service added'), ('removed', 'Service removed')], max_length=64)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='calendar_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.calendarexception'),
        ),
        migrations.AddIndex(
            model_name='calendarexception',
            index=models.Index(fields=['feed_id', 'service_id'], name='gtfs_calend_feed_id_790439_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarexception',
            unique_together={('feed_id', 'calendar', 'service_id', 'date')},
        ),
    ]
