# Generated by Django 5.0.14 on 2025-09-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0009_calendarexception_trip_calendar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarexception',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='gtfs.calendar'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='gtfs.trip'),
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('shape_id', models.CharField(max_length=255, verbose_name='Shape ID')),
            ],
            options={
                'unique_together': {('feed_id', 'shape_id')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtfs.shape'),
        ),
        migrations.CreateModel(
            name='ShapePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sequence', models.PositiveIntegerField()),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gtfs.shape')),
            ],
        ),
    ]
