# Generated by Django 5.0.14 on 2025-09-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0010_alter_calendarexception_calendar_alter_stoptime_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtfsRtFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
