# Generated by Django 5.0.14 on 2025-09-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0011_gtfsrtfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled', models.BooleanField(blank=True, default=False)),
                ('last_updated', models.DateTimeField()),
                ('rt_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_updates', to='gtfs.gtfsrtfeed')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='gtfs.trip')),
            ],
        ),
    ]
