# Generated by Django 5.0.14 on 2025-09-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0012_tripupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('assigned_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.stop')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.stoptime')),
                ('trip_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.tripupdate')),
            ],
        ),
    ]
