# Generated by Django 5.0.14 on 2025-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0013_stopupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopupdate',
            name='skipped',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
