# Generated by Django 5.0.14 on 2025-09-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0014_stopupdate_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopupdate',
            name='trip_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='gtfs.tripupdate'),
        ),
        migrations.AlterUniqueTogether(
            name='shapepoint',
            unique_together={('shape', 'sequence')},
        ),
    ]
