# Generated by Django 5.0.14 on 2025-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0015_alter_stopupdate_trip_update_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendarexception',
            constraint=models.UniqueConstraint(condition=models.Q(('service_id', None)), fields=('feed_id', 'calendar', 'date'), name='unique_calendar'),
        ),
        migrations.AddConstraint(
            model_name='calendarexception',
            constraint=models.UniqueConstraint(condition=models.Q(('calendar', None)), fields=('feed_id', 'service_id', 'date'), name='unique_service_id'),
        ),
    ]
