# Generated by Django 5.0.14 on 2025-09-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0016_calendarexception_unique_calendar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarexception',
            unique_together=set(),
        ),
    ]
