# Generated by Django 5.0.14 on 2025-09-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0017_alter_calendarexception_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=255, verbose_name='Feed ID')),
                ('service_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calendar ID')),
                ('date', models.DateField()),
                ('exception', models.CharField(choices=[('added', 'Service added'), ('removed', 'Service removed')], max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='calendarexception',
            name='unique_calendar',
        ),
        migrations.RemoveConstraint(
            model_name='calendarexception',
            name='unique_service_id',
        ),
        migrations.RemoveIndex(
            model_name='calendarexception',
            name='gtfs_calend_feed_id_790439_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calendarexception',
            unique_together={('feed_id', 'calendar', 'date')},
        ),
        migrations.AddIndex(
            model_name='calendarexception',
            index=models.Index(fields=['feed_id', 'calendar'], name='gtfs_calend_feed_id_c9680b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['feed_id', 'service_id'], name='gtfs_calend_feed_id_2f0aa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('feed_id', 'service_id', 'date')},
        ),
        migrations.AlterField(
            model_name='trip',
            name='calendar_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.calendardate'),
        ),
        migrations.RemoveField(
            model_name='calendarexception',
            name='service_id',
        ),
    ]
