# Generated by Django 5.0.14 on 2025-09-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0018_calendardate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendardate',
            name='gtfs_calend_feed_id_2f0aa5_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarexception',
            name='gtfs_calend_feed_id_c9680b_idx',
        ),
        migrations.AlterIndexTogether(
            name='calendardate',
            index_together={('date', 'exception')},
        ),
    ]
