# Generated by Django 5.0.14 on 2025-09-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0019_remove_calendardate_gtfs_calend_feed_id_2f0aa5_idx_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='calendardate',
            index_together={('date', 'exception'), ('feed_id', 'service_id')},
        ),
        migrations.AlterIndexTogether(
            name='calendarexception',
            index_together={('feed_id', 'calendar')},
        ),
    ]
