# Generated by Django 5.0.14 on 2025-09-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0020_alter_calendardate_index_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stopupdate',
            unique_together={('trip_update', 'stop')},
        ),
        migrations.AlterUniqueTogether(
            name='tripupdate',
            unique_together={('rt_feed', 'trip')},
        ),
    ]
