# Generated by Django 5.0.9 on 2025-03-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_account_bahnbonus_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sbahn_berlin_device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S-Bahn Berlin Device ID'),
        ),
        migrations.AddField(
            model_name='account',
            name='sbahn_berlin_token',
            field=models.TextField(blank=True, null=True, verbose_name='S-Bahn Berlin Token'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sbahn_berlin_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbahn_berlin_tickets', to='main.account'),
        ),
    ]
