# Generated by Django 5.0.9 on 2025-03-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_account_sbahn_berlin_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='saarvv_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saarvv_tickets', to='main.account', verbose_name='SaarVV Account'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sbahn_berlin_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbahn_berlin_tickets', to='main.account', verbose_name='S-Bahn Berlin Account'),
        ),
        migrations.CreateModel(
            name='VDVSmartcard',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fci', models.BinaryField()),
                ('application_directory', models.BinaryField()),
                ('ca_cert', models.BinaryField()),
                ('application_cert', models.BinaryField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vdv_smartcards', to='main.account')),
            ],
        ),
    ]
