# Generated by Django 5.0.9 on 2025-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_ticket_saarvv_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vdvsmartcard',
            options={'verbose_name': 'VDV Smartcard', 'verbose_name_plural': 'VDV Smartcards'},
        ),
        migrations.AddField(
            model_name='vdvsmartcard',
            name='atr_application_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vdvsmartcard',
            name='atr_historical_bytes',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vdvsmartcard',
            name='atr_identifier',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
