# Generated by Django 5.0.9 on 2025-04-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_vdvsmartcardlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vdvsmartcardlog',
            options={'verbose_name': 'VDV Smartcard Log Entry', 'verbose_name_plural': 'VDV Smartcard Log Entries'},
        ),
    ]
