# Generated by Django 5.0.9 on 2025-04-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_account_avv_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('deutschlandticket', 'Deutschlandticket'), ('klimaticket', 'Klimaticket'), ('bahncard', 'Bahncard'), ('fahrkarte', 'Travel ticket'), ('bordkarte', 'Boarding card'), ('reservierung', 'Reservation'), ('interrail', 'Interrail'), ('railcard', 'Railcard'), ('keycard', 'Keycard'), ('bahnbonus', 'BahnBonus'), ('unknown', 'Unknown')], default='unknown', max_length=255, verbose_name='Ticket type'),
        ),
        migrations.CreateModel(
            name='AccountOAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=255, verbose_name='Provider')),
                ('token', models.TextField(blank=True, null=True, verbose_name='Bearer token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Bearer token expiration')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh token')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Refresh token expiration')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth', to='main.account')),
            ],
        ),
    ]
