# Generated by Django 5.0.9 on 2025-04-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_ticket_ticket_type_accountoauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountoauth',
            options={'verbose_name': 'Account OAuth', 'verbose_name_plural': 'Account OAuths'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='oauth_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.accountoauth', verbose_name='OAuth Account'),
        ),
    ]
