# Generated by Django 5.0.9 on 2025-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_accountoauth_options_ticket_oauth_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountoauth',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID'),
        ),
    ]
