# Generated by Django 5.0.9 on 2025-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_accountoauth_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountoauth',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='accesslogentry',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='photos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
