# Generated by Django 5.0.9 on 2025-04-23 19:28

from django.db import migrations

from main.views.saarvv import saarvv_account


def move_tokens(apps, schema_editor):
    Account = apps.get_model('main', 'Account')
    AccountOAuth = apps.get_model('main', 'AccountOAuth')
    Ticket = apps.get_model('main', 'Ticket')
    for account in Account.objects.all():
        if account.db_token:
            if not AccountOAuth.objects.filter(account=account, provider="db").exists():
                AccountOAuth.objects.create(
                    account=account, provider="db",
                    token=account.db_token,
                    token_expires_at=account.db_token_expires_at,
                    refresh_token=account.db_refresh_token,
                    refresh_token_expires_at=account.db_refresh_token_expires_at,
                    extra_data={
                        "account_id": account.db_account_id,
                    }
                )

        if account.bahnbonus_token:
            if not AccountOAuth.objects.filter(account=account, provider="bahnbonus").exists():
                AccountOAuth.objects.create(
                    account=account, provider="bahnbonus",
                    token=account.bahnbonus_token,
                    token_expires_at=account.bahnbonus_token_expires_at,
                    refresh_token=account.bahnbonus_refresh_token,
                    refresh_token_expires_at=account.bahnbonus_refresh_token_expires_at,
                )

        if account.avv_token:
            if not AccountOAuth.objects.filter(account=account, provider="avv").exists():
                AccountOAuth.objects.create(
                    account=account, provider="avv",
                    token=account.avv_token,
                    token_expires_at=account.avv_token_expires_at,
                    refresh_token=account.avv_refresh_token,
                    refresh_token_expires_at=account.avv_refresh_token_expires_at,
                    device_id=account.avv_device_id,
                )

        if account.saarvv_token:
            if not AccountOAuth.objects.filter(account=account, provider="saarvv").exists():
                AccountOAuth.objects.create(
                    account=account, provider="saarvv",
                    token=account.saarvv_token,
                    device_id=account.saarvv_device_id,
                )

        if account.sbahn_berlin_token:
            if not AccountOAuth.objects.filter(account=account, provider="sbahn_berlin").exists():
                AccountOAuth.objects.create(
                    account=account, provider="sbahn_berlin",
                    token=account.sbahn_berlin_token,
                    device_id=account.sbahn_berlin_device_id,
                )

    for ticket in Ticket.objects.filter(saarvv_account__isnull=False):
        if o := AccountOAuth.objects.filter(account=ticket.saarvv_account, provider="saarvv").first():
            ticket.oauth_account = o
            ticket.save()

    for ticket in Ticket.objects.filter(avv_account__isnull=False):
        if o := AccountOAuth.objects.filter(account=ticket.avv_account, provider="avv").first():
            ticket.oauth_account = o
            ticket.save()

    for ticket in Ticket.objects.filter(sbahn_berlin_account__isnull=False):
        if o := AccountOAuth.objects.filter(account=ticket.sbahn_berlin_account, provider="sbahn_berlin").first():
            ticket.oauth_account = o
            ticket.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0065_accountoauth_extra_data_alter_accesslogentry_headers_and_more'),
    ]

    operations = [
        migrations.RunPython(move_tokens, lambda a, s: None),
        migrations.RemoveField(
            model_name='account',
            name='avv_device_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='avv_refresh_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='avv_refresh_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='avv_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='avv_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bahnbonus_refresh_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bahnbonus_refresh_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bahnbonus_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bahnbonus_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='db_account_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='db_refresh_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='db_refresh_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='db_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='db_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saarvv_device_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saarvv_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sbahn_berlin_device_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sbahn_berlin_token',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='avv_account',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='saarvv_account',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sbahn_berlin_account',
        ),
    ]
