# Generated by Django 5.0.14 on 2025-05-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_remove_account_avv_device_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vdvsmartcardlog',
            options={'ordering': ('sequence_number',), 'verbose_name': 'VDV Smartcard Log Entry', 'verbose_name_plural': 'VDV Smartcard Log Entries'},
        ),
        migrations.CreateModel(
            name='FlexiTicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issuer_id', models.CharField(db_index=True, max_length=2, verbose_name='Issuer ID')),
                ('barcode_data', models.BinaryField()),
                ('decoded_data', models.JSONField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ft_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'Flexi-ticket',
            },
        ),
    ]
