# Generated by Django 5.0.14 on 2025-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_vdvsmartcardlog_options_flexiticketinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label'),
        ),
    ]
