# Generated by Django 5.0.14 on 2025-05-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_ticket_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttidoDevice',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Device ID')),
                ('push_token', models.CharField(max_length=255, verbose_name='Push token')),
                ('push_service_url', models.CharField(max_length=255, verbose_name='Push service url')),
            ],
        ),
        migrations.CreateModel(
            name='AttidoRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_part', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket part')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.attidodevice')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attido_registrations', to='main.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'device', 'ticket_part')},
            },
        ),
    ]
