# Generated by Django 5.0.14 on 2025-05-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_attidodevice_attidoregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDVBlocklistMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'VDV Blocklist Meta',
            },
        ),
        migrations.CreateModel(
            name='VDVBlocklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('nm', 'Nutzermedium'), ('ber', 'Berechtigung')], max_length=10)),
                ('kvp_org_id', models.PositiveIntegerField()),
                ('item_id', models.PositiveIntegerField()),
                ('instance_counter', models.PositiveIntegerField(default=0)),
                ('lock_mode', models.PositiveIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Lock'), (2, 'Unlock')], default=0)),
            ],
            options={
                'verbose_name': 'VDV Blocklist Item',
                'verbose_name_plural': 'VDV Blocklist Items',
                'unique_together': {('item_type', 'kvp_org_id', 'item_id')},
            },
        ),
    ]
