# Generated by Django 5.0.14 on 2025-05-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_vdvblocklistmeta_vdvblocklistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vdvblocklistitem',
            unique_together={('item_type', 'kvp_org_id', 'item_id', 'instance_counter')},
        ),
        migrations.AlterIndexTogether(
            name='vdvblocklistitem',
            index_together={('item_type', 'kvp_org_id', 'item_id', 'instance_counter')},
        ),
    ]
