# Generated by Django 5.0.14 on 2025-05-17 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_vdvblocklistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vdvblocklistitem',
            old_name='kvp_org_id',
            new_name='org_id',
        ),
        migrations.AlterUniqueTogether(
            name='vdvblocklistitem',
            unique_together={('item_type', 'org_id', 'item_id', 'instance_counter')},
        ),
        migrations.AlterIndexTogether(
            name='vdvblocklistitem',
            index_together={('item_type', 'org_id', 'item_id'), ('item_type', 'org_id', 'item_id', 'instance_counter')},
        ),
        migrations.AddField(
            model_name='vdvblocklistitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
