# Generated by Django 5.0.14 on 2025-05-17 13:26

from django.db import migrations, models
from main.models import VDVTicketInstance

def set_ticket_id(apps, schema_editor):
    model = apps.get_model("main", "VDVTicketInstance")
    for i in model.objects.all():
        try:
            t = VDVTicketInstance._as_ticket(i)
        except Exception as e:
            print(e)
            continue
        i.ticket_num = t.ticket.ticket_id
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_rename_kvp_org_id_vdvblocklistitem_org_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_revocation', 'View the revocation status of tickets')]},
        ),
        migrations.AddField(
            model_name='vdvticketinstance',
            name='ticket_num',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ticket ID'),
            preserve_default=False,
        ),
        migrations.RunPython(set_ticket_id, lambda a, s: None),
        migrations.AlterIndexTogether(
            name='vdvticketinstance',
            index_together={('ticket_org_id', 'ticket_num')},
        ),
    ]
