# Generated by Django 5.0.14 on 2025-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_alter_ticket_options_vdvticketinstance_ticket_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdvblocklistitem',
            name='item_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vdvblocklistitem',
            name='item_type',
            field=models.CharField(choices=[('nm', 'Nutzermedium'), ('ber', 'Berechtigung')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vdvblocklistitem',
            name='org_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
