# Generated by Django 5.0.14 on 2025-05-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_vdvblocklistitem_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidPassDevice',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Device ID')),
                ('push_token', models.CharField(max_length=255, verbose_name='Push token')),
            ],
        ),
        migrations.CreateModel(
            name='AndroidPassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_part', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket part')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.androidpassdevice')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='android_pass_registrations', to='main.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'device', 'ticket_part')},
            },
        ),
    ]
