# Generated by Django 5.0.14 on 2025-05-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_androidpassdevice_androidpassregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDVSmartcardAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_number', models.IntegerField()),
                ('authorization_org_id', models.IntegerField()),
                ('authorization', models.BinaryField()),
                ('smartcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='main.vdvsmartcard')),
            ],
            options={
                'verbose_name': 'VDV Smartcard Authorization',
                'verbose_name_plural': 'VDV Smartcard Authorizations',
                'ordering': ('authorization_number',),
                'unique_together': {('smartcard', 'authorization_number', 'authorization_org_id')},
            },
        ),
    ]
