# Generated by Django 5.0.14 on 2025-05-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_vdvsmartcardauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdvsmartcardauthorization',
            name='info_text',
            field=models.TextField(blank=True),
        ),
    ]
