# Generated by Django 5.0.14 on 2025-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_vdvsmartcardauthorization_info_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownRailEasyJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_id', models.CharField(max_length=255)),
                ('purchase_id', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('journey_id', 'purchase_id')},
            },
        ),
    ]
