# Generated by Django 5.0.14 on 2025-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_ts2instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicticketinstance',
            name='reported',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vdvticketinstance',
            name='reported',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
