# Generated by Django 5.0.14 on 2025-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_uicticketinstance_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='suspected_fraud',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
