# Generated by Django 5.0.14 on 2025-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_ticket_suspected_fraud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslogentry',
            options={'verbose_name_plural': 'Access Log Entries'},
        ),
        migrations.AlterField(
            model_name='uicticketinstance',
            name='issuing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
