# Generated by Django 5.0.14 on 2025-09-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_accesslogentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateExpansions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forename')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Surname')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_expansions', to='main.account')),
            ],
        ),
    ]
