# Generated by Django 5.0.14 on 2025-10-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alternateexpansions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdvblocklistitem',
            name='lock_mode',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Confiscate'), (2, 'Suspicious')], default=0),
        ),
        migrations.CreateModel(
            name='SNCBTrainPlusInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('barcode_data', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sncb_trainplus_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'SNCB Train+',
            },
        ),
    ]
