# Generated by Django 5.0.14 on 2025-11-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_adifinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTVGBlocklistMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DTVG Blocklist Meta',
            },
        ),
    ]
