# Generated by Django 5.0.14 on 2025-11-03 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_dtvgblocklistmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTVGBlocklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rics', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='RICS')),
                ('ticket_id', models.CharField(db_index=True, max_length=64, verbose_name='Ticket ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DTVG Blocklist Item',
                'verbose_name_plural': 'DTVG Blocklist Items',
                'unique_together': {('rics', 'ticket_id')},
                'index_together': {('rics', 'ticket_id')},
            },
        ),
    ]
