# Generated by Django 5.0.14 on 2025-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_dtvgblocklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_issuer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
