# Generated by Django 5.0.14 on 2025-11-25 08:28

from django.db import migrations, models
from main.models import UICTicketInstance

def set_ticket_id(apps, schema_editor):
    model = apps.get_model("main", "UICTicketInstance")
    for i in model.objects.all():
        try:
            t = UICTicketInstance._as_ticket(i)
        except Exception as e:
            print(e)
            continue
        i.ticket_pnr = t.ticket_id()
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_ticket_issuer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicticketinstance',
            name='ticket_pnr',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Ticket ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='admin_issuer_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Issuer ID'),
        ),
        migrations.RunPython(set_ticket_id, lambda a, s: None),
        migrations.AlterIndexTogether(
            name='uicticketinstance',
            index_together={('distributor_rics', 'ticket_pnr')},
        ),
    ]
