# Generated by Django 5.0.14 on 2025-12-01 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_uicticketinstance_ticket_pnr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MavInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_rics', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Distributor RICS')),
                ('barcode_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('barcode_data', models.BinaryField()),
                ('decoded_data', models.JSONField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mav_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'MÁV Ticket',
            },
        ),
    ]
