# Generated by Django 5.0.14 on 2026-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_mavinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownEOSTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=255)),
                ('ticket_id', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('operator_id', 'ticket_id')},
            },
        ),
    ]
